#!/bin/sh
set -e

errors=$(FPM_BIN --fpm-config FPM_CONF -t 2>&1 | grep "ERROR" || true);
if [ -n "$errors" ]; then
    echo "Please fix your configuration file..."
    echo $errors
    exit 1
fi
exit 0
